name: agentapi-claude-server
region: nyc1

services:
- name: agentapi-server
  source_dir: /
  github:
    repo: coder/agentapi
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 3284
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /status
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: PORT
    value: "3284"
  - key: NODE_ENV
    value: "production"
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME
    type: SECRET

alerts:
- rule: CPU_UTILIZATION
  value: 80
- rule: MEM_UTILIZATION
  value: 80 